import { url } from "inspector";

const projects = [
  {
    id: 1,
    slug: "xpower-platform",
    url: "https://www.xcellen.com/",
    title: "Xpower Platform – Sales Force Effectiveness",
    desc: "A sales force effectiveness platform for the life sciences industry with modules for customer targeting, territory management, and sales planning.",
    type: "Web Application",
    status: "in progress",
    date: "Jun 2020 – Present",
    featured: true,
    image: "project-xpower.png",
    tags: ["Angular 14", "TypeScript", "Bootstrap 4.6", "Plotly", "Mapbox"],
    overview:
      "Developed responsive and interactive user interfaces for Xpower using Angular and Bootstrap. Enhanced sales operations through advanced dashboards and UI components.",
    features: [
      "Customer targeting with data-driven UI",
      "Territory management with Mapbox",
      "Sales target setting dashboards",
      "Incentive planning module",
      "Data visualization with Plotly charts",
    ],
    technologies: {
      frontend: ["Angular 14", "Bootstrap 4.6", "UI-Grid", "ag-Grid"],
      backend: ["Node.js"],
    },
    metrics: {
      duration: "4+ years",
      teamSize: 5,
      technologies: 7,
      status: "In Progress",
      users: "Pharma sales teams (500+ users)",
    },
    roles: ["Frontend Developer", "UI Developer", "Tester"],
    timeline: [
      { phase: "Customer Targeting", duration: "Jun 2020 – Present" },
      { phase: "Sales Target Setting", duration: "Jun 2020 – Feb 2023" },
      { phase: "Incentive Planning", duration: "Feb 2023 – Aug 2024" },
      { phase: "Territory Management", duration: "Feb 2023 – Present" },
    ],
    achievements: [
      "Improved territory optimization with geospatial dashboards",
      "Streamlined sales allocation process",
      "Delivered incentive planning features boosting sales motivation",
    ],
    challenges: ["Handling large-scale pharma datasets", "Integration with multiple APIs"],
    nextSteps: ["Expand analytics features", "AI-based segmentation"],
  },
  {
    id: 2,
    slug: "igis-map",
    url: "https://www.igismap.com/",
    title: "IGIS Map – Interactive Web Maps",
    desc: "Tool for building interactive web maps with advanced visualization and analysis features.",
    type: "Website",
    status: "completed",
    date: "2017 – 2020",
    featured: true,
    image: "project-igis.png",
    tags: ["Angular 8", "Angular 14", "Bootstrap 4.6", "JavaScript", "UI/UX"],
    overview:
      "Designed and developed custom interactive mapping solutions with Angular, Bootstrap, and custom UI components.",
    features: [
      "Dynamic map rendering",
      "Custom UI components",
      "Data visualization integration",
      "Responsive design",
    ],
    technologies: {
      frontend: ["Angular 8/14", "Bootstrap 4.6", "Angular Material","UI/UX"],
      backend: [],
    },
    metrics: {
      duration: "3 years",
      teamSize: 3,
      technologies: 5,
      status: "Completed",
      users: "GIS professionals",
    },
    roles: ["UI Developer", "Frontend Developer"],
    timeline: [
      { phase: "Design", duration: "6 months" },
      { phase: "Development", duration: "2.5 years" },
    ],
    achievements: [
      "Delivered enterprise-grade map platform",
      "Built responsive UIs for GIS tools",
    ],
    challenges: ["Complex map integrations", "UI performance"],
    nextSteps: ["Add AI-based spatial insights"],
  },
  {
    id: 3,
    slug: "engineer-philosophy",
    url: "https://www.engineerphilosophy.com/",
    title: "Engineer Philosophy Web Application",
    desc: "Dynamic responsive websites built from PSD to Angular components.",
    type: "Website",
    status: "completed",
    date: "2017 – 2018",
    featured: true,
    image: "project-engineer.png",
    tags: ["Angular 8", "Angular Material", "HTML", "CSS"," UI/UX","Bootstrap 3.36","Photoshop"],
    overview:
      "Converted PSD designs into responsive Angular apps ensuring cross-browser compatibility.",
    features: [
      "Pixel-perfect PSD to Angular conversion",
      "Reusable Angular Material components",
      "Cross-browser compatibility",
    ],
    technologies: {
      frontend: ["Angular 8", "Angular Material", "HTML5", "CSS3", "Bootstrap 3.36", "Photoshop"],
      backend: [],
    },
    metrics: {
      duration: "6 months",
      teamSize: 2,
      technologies: 4,
      status: "Completed",
      users: "Internal & client websites",
    },
    roles: ["Frontend Developer", "UI Designer"],
    timeline: [
      { phase: "Planning", duration: "1 month" },
      { phase: "Development", duration: "5 months" },
    ],
    achievements: ["Delivered responsive Angular apps", "Ensured cross-browser support"],
    challenges: ["Maintaining pixel perfection", "Browser inconsistencies"],
    nextSteps: ["Enhance with modern frameworks"],
  },
  {
    id: 4,
    slug: "ssv-technologies",
    url: "https://ssvtechnologies.in/",
    title: "SSV Technologies – Client Websites",
    desc: "Multiple responsive client websites delivered with HTML, CSS, and Bootstrap.",
    type: "Website",
    status: "completed",
    date: "2014 – 2017",
    featured: true,
    image: "project-ssv.png",
    tags: ["HTML5", "CSS3", "Bootstrap" ,"Photoshop","CorelDRAW"],
    overview:
      "Designed and delivered 25+ responsive websites for small and medium businesses.",
    features: [
      "Clean modern layouts",
      "Cross-browser compatibility",
      "Mobile responsiveness",
    ],
    technologies: {
      frontend: ["HTML5", "CSS3", "Bootstrap 3/4", "Photoshop", "CorelDRAW"],
      backend: [],
    },
    metrics: {
      duration: "2.5 years",
      teamSize: 3,
      technologies: 3,
      status: "Completed",
      users: "SMBs & clients",
    },
    roles: ["Web Designer", "Frontend Developer"],
    timeline: [
      { phase: "Design", duration: "6 months" },
      { phase: "Development", duration: "2 years" },
    ],
    achievements: ["25+ client websites delivered", "Optimized responsive designs"],
    challenges: ["Meeting strict deadlines", "Maintaining consistency"],
    nextSteps: ["Expand to CMS-based websites"],
  },
  {
    id: 5,
    slug: "freelance-pisarv",
    url: "http://pisarv.com/",
    title: "Freelance – PISARV Websites",
    desc: "Freelance projects delivering responsive websites for PISARV and other clients.",
    type: "Website",
    status: "completed",
    date: "Jul 2021 – Oct 2021",
    featured: true,
    image: "project-pisarv.png",
    tags: ["HTML", "CSS", "Bootstrap"],
    overview:
      "Developed responsive websites for clients ensuring mobile optimization and user-friendly UI.",
    features: [
      "Cross-browser compatibility",
      "Wireframes & mockups",
      "Responsive design",
    ],
    technologies: {
      frontend: ["HTML", "CSS", "Bootstrap 3.36"],
      backend: [],
    },
    metrics: {
      duration: "3 months",
      teamSize: 1,
      technologies: 3,
      status: "Completed",
      users: "Multiple freelance clients",
    },
    roles: ["Frontend Developer", "UI Designer"],
    timeline: [
      { phase: "Planning", duration: "1 month" },
      { phase: "Development", duration: "2 months" },
    ],
    achievements: ["Delivered pixel-perfect websites", "Improved client UX"],
    challenges: ["Handling multiple clients at once"],
    nextSteps: ["Take on larger freelance projects"],
  },
  {
    id: 6,
    slug: "web-portfolio",
    url: "https://dev-narendra.vercel.app/",
    title: "Personal Web Portfolio",
    desc: "My personal portfolio website built with Next.js and Tailwind CSS to showcase my skills and projects.",
    type: "website",
    status: "in progress",
    date: "2025",
    featured: true,
    image: "project-portfolio.png",
    tags: ["Next.js", "TypeScript", "Tailwind CSS"],
    overview:
      "A modern developer portfolio built with Next.js and Tailwind CSS to showcase my projects, skills, and career journey.",
    features: [
      "Responsive modern UI",
      "Dark/light theme toggle",
      "Project showcase with details",
      "SEO optimized structure",
    ],
    technologies: {
      frontend: ["Next.js", "TypeScript", "Tailwind CSS"],
      backend: ["Static Site Generation (SSG)", "Vercel Hosting"],
    },
    metrics: {
      duration: "Ongoing",
      teamSize: 1,
      technologies: 3,
      status: "In Progress",
      users: "Public visitors",
    },
    roles: ["Frontend Developer", "Designer"],
    timeline: [
      { phase: "Planning", duration: "2 weeks" },
      { phase: "Development", duration: "Ongoing" },
    ],
    achievements: ["Portfolio hosted on Vercel", "Clean minimal design"],
    challenges: ["Keeping content easily maintainable"],
    nextSteps: ["Add blog section", "Integrate CMS"],
  },
];

export default projects;
